# Week 3 Monday


## Screenshare notes

![Slide 1](images/W3M/1.gif)

![Slide 2](images/W3M/2.gif)

![Slide 3](images/W3M/3.gif)

## Deepnote notebook

Today's class is mostly devoted to helping you better understand Lab 2, where you will perform a Diffie-Hellman Key Exchange with another group.

In [ ]:
!pip install pycryptodome

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 86.1 MB/s eta 0:00:00
You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [ ]:
from Crypto.Util.number import getPrime, getRandomNBitInteger
from sympy.ntheory import n_order, nextprime, isprime

In [ ]:
p = getPrime(10)

In [ ]:
p

683

The `10` in `getPrime(10)` refers to how many digits the prime is when written in binary.

In [ ]:
pow(2, 10)

1024

In [ ]:
pow(2, 9)

512

For example, a 30 digit prime (in ordinary base 10 digits) is between $10^{29}$ and $10^{30}$.  Similarly, a 30-bit prime (meaning 30 digits in binary, in base 2) is between $2^{29}$ and $2^{30}$.

In [ ]:
getPrime(30)

803359783

In [ ]:
pow(2, 29)

536870912

In [ ]:
pow(2, 30)

1073741824

In [ ]:
p

683

Let's find a generator modulo p = 683.

In [ ]:
n_order(1, p)

1

In [ ]:
n_order(2, p)

22

In [ ]:
# Want p-1
p-1

682

In [ ]:
n_order(0, p)

ValueError: The two numbers should be relatively prime

In [ ]:
n_order(3, p)

31

In [ ]:
# Check: do these orders divide the size of the group (p-1)
(p-1)/22

31.0

In [ ]:
(p-1)/31

22.0

In [ ]:
# Not quite what we want
22%(p-1)

22

In [ ]:
# Fancier way to check that 22 divides p-1, using `%`
# For example, 27%11 is 5
(p-1)%22

0

In [ ]:
gens_list = []
for g in range(1, p):
    if n_order(g, p) == p-1:
        gens_list.append(g)

In [ ]:
# Secretly this list has length phi(p-1), where phi(p-1) is the size of (Z/(p-1)Z)^x
print(gens_list)

[5, 6, 7, 11, 13, 15, 17, 18, 20, 21, 23, 24, 28, 31, 33, 38, 39, 41, 43, 44, 45, 47, 50, 51, 52, 54, 58, 60, 63, 68, 69, 70, 72, 73, 79, 84, 89, 92, 93, 95, 96, 98, 99, 106, 107, 110, 113, 114, 117, 118, 122, 123, 125, 129, 130, 131, 132, 133, 134, 135, 139, 141, 142, 145, 148, 149, 150, 152, 153, 154, 156, 157, 162, 164, 166, 170, 172, 174, 175, 176, 179, 180, 181, 182, 188, 189, 194, 199, 200, 202, 203, 204, 206, 207, 208, 209, 210, 216, 218, 219, 223, 230, 232, 237, 238, 242, 245, 247, 251, 252, 254, 263, 267, 271, 272, 274, 275, 276, 277, 279, 280, 283, 285, 286, 288, 294, 295, 297, 302, 305, 307, 310, 318, 319, 320, 321, 322, 323, 326, 330, 331, 334, 335, 338, 339, 343, 346, 351, 354, 355, 356, 359, 366, 368, 369, 370, 374, 375, 377, 379, 380, 382, 383, 384, 385, 387, 390, 392, 393, 394, 396, 399, 401, 402, 405, 410, 413, 415, 417, 419, 421, 422, 423, 424, 425, 426, 428, 434, 435, 437, 439, 442, 444, 447, 448, 449, 450, 452, 454, 456, 457, 458, 459, 461, 462, 463, 466, 468, 469, 

In [ ]:
len(gens_list)

300

In [ ]:
p-1

682

In [ ]:
from math import gcd

In [ ]:
# What is (Z/682Z)^x?
N = p-1
elt_list = []
for a in range(N):
    if gcd(a, N) == 1:
        elt_list.append(a)

In [ ]:
len(elt_list)

300

In [ ]:
print(elt_list)

[1, 3, 5, 7, 9, 13, 15, 17, 19, 21, 23, 25, 27, 29, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 79, 81, 83, 85, 87, 89, 91, 95, 97, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 145, 147, 149, 151, 153, 157, 159, 161, 163, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 211, 213, 215, 219, 221, 223, 225, 227, 229, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 277, 281, 283, 285, 287, 289, 291, 293, 295, 299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 321, 323, 325, 327, 329, 331, 333, 335, 337, 339, 343, 345, 347, 349, 351, 353, 355, 357, 359, 361, 365, 367, 369, 371, 373, 375, 377, 379, 381, 383, 387, 389, 391, 393, 395, 397, 399, 401, 405, 409, 411, 413, 415, 417, 419, 421, 423, 425, 427, 431, 433, 435, 437, 439, 441, 443, 445, 447, 449, 453, 455, 457, 459, 461, 463, 467, 469, 471, 475, 47

Not at all obvious why these two sizes are equal.  It's a hard Math 120A exercise to convince yourself these are the same.

Main thing to notice for now: in general, there are lots of generators.  (300 of the 682 options in this case.)

In Lab 2, you don't need to find all of the generators, you just need to find one generator.

**Warning**: The primes you use in Lab 2 should be much bigger than 683.

In [ ]:
# This is still naive, still slow, but better than what I wrote in Homework 2.
def better_naive_dlog(g, h, p):
    '''This will be the first positive value x such that g^x mod p == h, if it exists'''
    y = 1 # This is g^0 mod p
    for x in range(1, p):
        # compute y = g^x mod p assuming y is currently g^(x-1) mod p
        # Could use y = pow(g, x, p), but let's take advantage of already knowing g^(x-1) mod p
        y = (y*g)%p
        if y == h:
            return x

    # If no solution exists, return None
    return None

In [ ]:
(7**43)%101

46

In [ ]:
better_naive_dlog(7, 46, 101)

43

In [ ]:
n_order(5, 101)

25

In [ ]:
pow(5, 87, 101)

92

In [ ]:
better_naive_dlog(5, 92, 101)

12

In [ ]:
pow(5, 12, 101)

92

In [ ]:
pow(5, 12+25, 101)

92

In [ ]:
pow(5, 62, 101)

92

As we've defined it, discrete logarithms have either 0 solutions or infinitely many solutions.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=49a6bd9c-13f9-4ae6-b1d4-bb1fccedca7d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>